from typing import AnyStr, Dict, Iterable, List, Tuple, Type

PY: Tuple[int, int]
PY2: bool
PY3: bool
PYPY: bool
ONWINDOWS: bool
stringtypes: Tuple[Type, ...]
integertypes: Tuple[Type, ...]
unicodestringtype = str
bytestringtype = bytes
INT2BYTE_CACHE: Dict[int, bytes]

def int2byte(character: int) -> bytes: ...
def byte2int(character: bytes) -> int: ...
def str2bytes(string: str) -> bytes: ...
def bytes2str(string: bytes) -> str: ...
def reprstring(data: AnyStr) -> str: ...
def trimstring(data: AnyStr) -> str: ...
def integers2bytes(ints: Iterable[int]) -> bytes: ...
def bytes2integers(data: bytes) -> List[int]: ...
